Used Different classes, some fixes, code-styling
Archangel37/Lesson3_User-sReaction pull request #2
Opened 2018-04-12 10:05 UTC by Archangel37

2018-04-13 05:18 UTC, ilpoli requested changes

2018-04-13 05:18 UTC, ilpoli commented on Lesson3_UserResponse/CalculateClicks.cs
> +    class CalculateClicks
так что это за класс и что он делает то? значения в него никакие не передаются, только считываются.

2018-04-13 07:44 UTC, Archangel37 commented on Lesson3_UserResponse/CalculateClicks.cs
> +    class CalculateClicks
Производит "вычисление" средних кликов, которые можно сделать за минуту, измерения проводятся парами - **дуплет** - передохнул пользователь, захотел улучшить время, ещё сделал пару кликов.. **Класс не связан с заданием**, просто для закрепления работы с временными интервалами.. Естественно, что можно было бы, к примеру, для вычисления среднего времени кликов и считать каждый и время каждого записывать, а потом дробить на временные интервалы, но в таком случае усложняется: реализация, механизм старт-стопа "теста" скорости кликанья по кнопке и у пользователя нет такой возможности передохнуть от кликов (там придётся не учитывать последний большой интервал и т.д.) - поэтому и реализация через два клика. Суть в том, что мы **условно считаем**, что пользователь может постоянно минуту кликать с той же частотой, что и сделал 2 клика - т.е. если между кликами 200мс, то УСЛОВНО можно сделать 5 интервалов кликов в секунду или 300 интервалов кликов в минуту - __*единица старта не учитывается*__, поэтому это условно равно 300 кликов в минуту при единственном результате в 200мс между кликами.. Естественно, что у пользователя разная скорость, разная скорость срабатывания мышки, отклик драйвера, системный обработчик и т.д., поэтому я беру каждый такой интервал(пара кликов), записываю в List интервалов, после для вычислений усредняю и делю минуту на средний интервал - получаю УСЛОВНОЕ СРЕДНЕЕ количество кликов в минуту **без учёта стартового**

2018-04-15 05:32 UTC, ilpoli approved these changes

2018-04-16 06:24 UTC, merged